# Generated by Django 4.2 on 2023-04-30 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_auto_20200516_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 4, 30, 20, 2, 55, 504818, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
