# Generated by Django 4.2 on 2023-04-30 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0016_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 4, 30, 20, 3, 48, 353548, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
