# Generated by Django 4.2 on 2023-05-02 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0018_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 5, 2, 19, 45, 43, 553499, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
