# Generated by Django 4.2 on 2023-05-29 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0023_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 5, 29, 16, 23, 1, 419989, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
