# Generated by Django 4.2 on 2023-05-30 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0024_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessanger_detail',
            name='username',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 5, 30, 8, 15, 56, 605066, tzinfo=datetime.timezone.utc), max_length=19),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='username',
            field=models.CharField(max_length=11),
        ),
    ]
