# Generated by Django 4.2 on 2023-06-15 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0029_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 6, 15, 22, 3, 34, 957985, tzinfo=datetime.timezone.utc), max_length=256),
        ),
    ]
