# Generated by Django 4.2 on 2023-06-17 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0032_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_desc',
            name='day1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='day6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 6, 17, 19, 27, 34, 800807, tzinfo=datetime.timezone.utc), max_length=256),
        ),
    ]
