# Generated by Django 4.2 on 2023-06-17 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0033_alter_detailed_desc_day1_alter_detailed_desc_day2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessanger_detail',
            name='country',
            field=models.CharField(default='Dhaka', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 6, 17, 20, 38, 24, 180364, tzinfo=datetime.timezone.utc), max_length=256),
        ),
    ]
